name: Archlinux
cas_config:
  local_cache_store: '/home/kate/TransferEfficiencyTool/local_cache/arch/'
  remote_storage:
    casync: 'http://127.0.0.1:8000/'
    desync: 'http://127.0.0.1:8000/'
  index_storage: '/home/kate/TransferEfficiencyTool/index/arch/'
  local_version_of_remote_storage: '/home/kate/TransferEfficiencyTool/remote_storage/arch/'
  chunk_sizes: [512, 768, 1024, 1536, 2048, 3072, 4096]
versions:
  - name: '20241110'
    src_path: 
      local: '/home/kate/TransferEfficiencyTool/test_data/arch/arch-20241110.tar'
      rsync: 'localhost:/home/kate/TransferEfficiencyTool/test_data/arch/arch-20241110.tar'
  - name: '20241117'
    src_path:
      local: '/home/kate/TransferEfficiencyTool/test_data/arch/arch-20241117.tar'
      rsync: 'localhost:/home/kate/TransferEfficiencyTool/test_data/arch/arch-20241117.tar'
  - name: '20241124'
    src_path:
      local: '/home/kate/TransferEfficiencyTool/test_data/arch/arch-20241124.tar'
      rsync: 'localhost:/home/kate/TransferEfficiencyTool/test_data/arch/arch-20241124.tar'
  - name: '20241201'
    src_path:
      local: '/home/kate/TransferEfficiencyTool/test_data/arch/arch-20241201.tar'
      rsync: 'localhost:/home/kate/TransferEfficiencyTool/test_data/arch/arch-20241201.tar'
  - name: '20241208'
    src_path:
      local: '/home/kate/TransferEfficiencyTool/test_data/arch/arch-20241208.tar'
      rsync: 'localhost:/home/kate/TransferEfficiencyTool/test_data/arch/arch-20241208.tar'
cas_transmitters:
  desync:
    port: 8000
other_transmitters:
  rsync:
    port: 22
result_data_store: '/home/kate/TransferEfficiencyTool/measurements/archlinux_optimal/'
result_plot_store: '/home/kate/TransferEfficiencyTool/measurements/archlinux_optimal/'
dest_path: '/home/kate/results/archlinux_optimal/{}.tar'
