name: ClickHouse
local_cache_store: '/home/kate/TransferEfficiencyTool/local_cache/clickhouse/'
remote_storage: 'http://127.0.0.1:8000/'
index_storage: '/home/kate/TransferEfficiencyTool/index/clickhouse/'
# rsync_remote_storage: 'localhost:/home/kate/TransferEfficiencyTool/index/clickhouse/'
versions: [
  ['jan', '/home/kate/TransferEfficiencyTool/test_data/ClickHouse/ClickHouse-jan', '/home/kate/TransferEfficiencyTool/results/ClickHouse/ClickHouse-jan'],
  ['feb', '/home/kate/TransferEfficiencyTool/test_data/ClickHouse/ClickHouse-feb', '/home/kate/TransferEfficiencyTool/results/ClickHouse/ClickHouse-feb'],
  ['mar', '/home/kate/TransferEfficiencyTool/test_data/ClickHouse/ClickHouse-mar', '/home/kate/TransferEfficiencyTool/results/ClickHouse/ClickHouse-mar'],
  ['apr', '/home/kate/TransferEfficiencyTool/test_data/ClickHouse/ClickHouse-apr', '/home/kate/TransferEfficiencyTool/results/ClickHouse/ClickHouse-apr'],
  ['may', '/home/kate/TransferEfficiencyTool/test_data/ClickHouse/ClickHouse-may', '/home/kate/TransferEfficiencyTool/results/ClickHouse/ClickHouse-may'],
  ['jun', '/home/kate/TransferEfficiencyTool/test_data/ClickHouse/ClickHouse-jun', '/home/kate/TransferEfficiencyTool/results/ClickHouse/ClickHouse-jun'],
  ['jul', '/home/kate/TransferEfficiencyTool/test_data/ClickHouse/ClickHouse-jul', '/home/kate/TransferEfficiencyTool/results/ClickHouse/ClickHouse-jul'],
  ['aug', '/home/kate/TransferEfficiencyTool/test_data/ClickHouse/ClickHouse-aug', '/home/kate/TransferEfficiencyTool/results/ClickHouse/ClickHouse-aug'], 
  ['sep', '/home/kate/TransferEfficiencyTool/test_data/ClickHouse/ClickHouse-sep', /home/kate/TransferEfficiencyTool/results/ClickHouse/ClickHouse-sep'],
  ['oct', '/home/kate/TransferEfficiencyTool/test_data/ClickHouse/ClickHouse-oct', '/home/kate/TransferEfficiencyTool/results/ClickHouse/ClickHouse-oct'],
  ['nov', '/home/kate/TransferEfficiencyTool/test_data/ClickHouse/ClickHouse-nov', '/home/kate/TransferEfficiencyTool/results/ClickHouse/ClickHouse-nov']
]
