name: ClickHouse
local_cache_store: '/home/kate/TransferEfficiencyTool/local_cache/clickhouse/'
remote_storage_casync: 'localhost:/home/kate/TransferEfficiencyTool/remote_storage/clickhouse/'
remote_storage_desync: 'http://127.0.0.1:8000/'
index_storage: '/home/kate/TransferEfficiencyTool/index/clickhouse/'
local_storage_for_casync_make: '/home/kate/TransferEfficiencyTool/remote_storage/clickhouse/'
dest_path: '/home/kate/results/clickhouse/{}'
versions:
  - name: 'jan'
    src_path: '/home/kate/test_data/clickhouse/ClickHouse-jan'
    rsync_src_path: 'localhost:/home/kate/test_data/clickhouse/ClickHouse-jan/'
  - name: 'feb'
    src_path: '/home/kate/test_data/clickhouse/ClickHouse-feb'
    rsync_src_path: 'localhost:/home/kate/test_data/clickhouse/ClickHouse-feb/'
  - name: 'mar'
    src_path: '/home/kate/test_data/clickhouse/ClickHouse-mar'
    rsync_src_path: 'localhost:/home/kate/test_data/clickhouse/ClickHouse-mar/'
  - name: 'apr'
    src_path: '/home/kate/test_data/clickhouse/ClickHouse-apr'
    rsync_src_path: 'localhost:/home/kate/test_data/clickhouse/ClickHouse-apr/'
  - name: 'may'
    src_path: '/home/kate/test_data/clickhouse/ClickHouse-may'
    rsync_src_path: 'localhost:/home/kate/test_data/clickhouse/ClickHouse-may/'
  - name: 'jun'
    src_path: '/home/kate/test_data/clickhouse/ClickHouse-jun'
    rsync_src_path: 'localhost:/home/kate/test_data/clickhouse/ClickHouse-jun/'
  - name: 'jul'
    src_path: '/home/kate/test_data/clickhouse/ClickHouse-jul'
    rsync_src_path: 'localhost:/home/kate/test_data/clickhouse/ClickHouse-jul/'
  - name: 'aug'
    src_path: '/home/kate/test_data/clickhouse/ClickHouse-aug'
    rsync_src_path: 'localhost:/home/kate/test_data/clickhouse/ClickHouse-aug/'
  - name: 'sep'
    src_path: '/home/kate/test_data/clickhouse/ClickHouse-sep'
    rsync_src_path: 'localhost:/home/kate/test_data/clickhouse/ClickHouse-sep/'
  - name: 'oct'
    src_path: '/home/kate/test_data/clickhouse/ClickHouse-oct'
    rsync_src_path: 'localhost:/home/kate/test_data/clickhouse/ClickHouse-oct/'
  - name: 'nov'
    src_path: '/home/kate/test_data/clickhouse/ClickHouse-nov'
    rsync_src_path: 'localhost:/home/kate/test_data/clickhouse/ClickHouse-nov/'
result_data_file: '/home/kate/TransferEfficiencyTool/results/clickhouse/clickhouse_ssh.yaml'
result_plot_file: '/home/kate/TransferEfficiencyTool/results/clickhouse/clickhouse_ssh.png'
