name: ClickHouse
cas_config:
  local_cache_store: '/home/kate/TransferEfficiencyTool/local_cache/clickhouse/'
  remote_storage:
    casync: 'localhost:/home/kate/TransferEfficiencyTool/remote_storage/clickhouse/'
    desync: 'http://127.0.0.1:8000/'
  index_storage: '/home/kate/TransferEfficiencyTool/index/clickhouse/'
  local_version_of_remote_storage: '/home/kate/TransferEfficiencyTool/remote_storage/clickhouse/'
  chunk_sizes: [512]
versions:
  - name: 'jan'
    src_path: 
      local: '/home/kate/test_data/clickhouse/ClickHouse-jan'
      rsync: 'localhost:/home/kate/test_data/clickhouse/ClickHouse-jan/'
      wget: 'http://localhost:8000/src/ClickHouse-jan.tar'
  - name: 'feb'
    src_path:
      local: '/home/kate/test_data/clickhouse/ClickHouse-feb'
      rsync: 'localhost:/home/kate/test_data/clickhouse/ClickHouse-feb/'
      wget: 'http://localhost:8000/src/ClickHouse-feb.tar'
  - name: 'mar'
    src_path:
      local: '/home/kate/test_data/clickhouse/ClickHouse-mar'
      rsync: 'localhost:/home/kate/test_data/clickhouse/ClickHouse-mar/'
      wget: 'http://localhost:8000/src/ClickHouse-mar.tar'
  - name: 'apr'
    src_path:
      local: '/home/kate/test_data/clickhouse/ClickHouse-apr'
      rsync: 'localhost:/home/kate/test_data/clickhouse/ClickHouse-apr/'
      wget: 'http://localhost:8000/src/ClickHouse-apr.tar'
  - name: 'may'
    src_path:
      local: '/home/kate/test_data/clickhouse/ClickHouse-may'
      rsync: 'localhost:/home/kate/test_data/clickhouse/ClickHouse-may/'
      wget: 'http://localhost:8000/src/ClickHouse-may.tar'
  - name: 'jun'
    src_path:
      local: '/home/kate/test_data/clickhouse/ClickHouse-jun'
      rsync: 'localhost:/home/kate/test_data/clickhouse/ClickHouse-jun/'
      wget: 'http://localhost:8000/src/ClickHouse-jun.tar'
  - name: 'jul'
    src_path:
      local: '/home/kate/test_data/clickhouse/ClickHouse-jul'
      rsync: 'localhost:/home/kate/test_data/clickhouse/ClickHouse-jul/'
      wget: 'http://localhost:8000/src/ClickHouse-jul.tar'
  - name: 'aug'
    src_path:
      local: '/home/kate/test_data/clickhouse/ClickHouse-aug'
      rsync: 'localhost:/home/kate/test_data/clickhouse/ClickHouse-aug/'
      wget: 'http://localhost:8000/src/ClickHouse-aug.tar'
  - name: 'sep'
    src_path:
      local: '/home/kate/test_data/clickhouse/ClickHouse-sep'
      rsync: 'localhost:/home/kate/test_data/clickhouse/ClickHouse-sep/'
      wget: 'http://localhost:8000/src/ClickHouse-sep.tar'
  - name: 'oct'
    src_path:
      local: '/home/kate/test_data/clickhouse/ClickHouse-oct'
      rsync: 'localhost:/home/kate/test_data/clickhouse/ClickHouse-oct/'
      wget: 'http://localhost:8000/src/ClickHouse-oct.tar'
  - name: 'nov'
    src_path:
      local: '/home/kate/test_data/clickhouse/ClickHouse-nov'
      rsync: 'localhost:/home/kate/test_data/clickhouse/ClickHouse-nov/'
      wget: 'http://localhost:8000/src/ClickHouse-nov.tar'
cas_transmitters:
  - casync
  - desync
other_transmitters:
  - wget
  - rsync
result_data_store: '/home/kate/TransferEfficiencyTool/measurements/clickhouse_wget/'
result_plot_store: '/home/kate/TransferEfficiencyTool/measurements/clickhouse_wget/'
dest_path: '/home/kate/results/clickhouse/{}'
