name: Debian
cas_config:
  local_cache_store: '/home/kate/TransferEfficiencyTool/local_cache/debian/'
  remote_storage:
    casync: 'localhost:/home/kate/TransferEfficiencyTool/remote_storage/debian/'
    desync: 'http://127.0.0.1:8000/'
  index_storage: '/home/kate/TransferEfficiencyTool/index/debian/'
  local_version_of_remote_storage: '/home/kate/TransferEfficiencyTool/remote_storage/debian/'
  chunk_sizes: [8, 16, 32, 64, 96, 128, 192, 256, 384, 512]
versions:
  - name: '12-0'
    src_path: 
      local: '/home/kate/TransferEfficiencyTool/test_data/debian/debian-12-0.tar'
      rsync: 'localhost:/home/kate/TransferEfficiencyTool/test_data/debian/debian-12-0.tar'
      zsync: 'http://localhost:8080/debian/debian-12-0.tar.zsync'
      zsync_local: '/var/www/remote_storage/debian/debian-12-0.tar'
  - name: '12-1'
    src_path: 
      local: '/home/kate/TransferEfficiencyTool/test_data/debian/debian-12-1.tar'
      rsync: 'localhost:/home/kate/TransferEfficiencyTool/test_data/debian/debian-12-1.tar'
      zsync: 'http://localhost:8080/debian/debian-12-1.tar.zsync'
      zsync_local: '/var/www/remote_storage/debian/debian-12-1.tar'
  - name: '12-2'
    src_path: 
      local: '/home/kate/TransferEfficiencyTool/test_data/debian/debian-12-2.tar'
      rsync: 'localhost:/home/kate/TransferEfficiencyTool/test_data/debian/debian-12-2.tar'
      zsync: 'http://localhost:8080/debian/debian-12-2.tar.zsync'
      zsync_local: '/var/www/remote_storage/debian/debian-12-2.tar'
  - name: '12-4'
    src_path: 
      local: '/home/kate/TransferEfficiencyTool/test_data/debian/debian-12-4.tar'
      rsync: 'localhost:/home/kate/TransferEfficiencyTool/test_data/debian/debian-12-4.tar'
      zsync: 'http://localhost:8080/debian/debian-12-4.tar.zsync'
      zsync_local: '/var/www/remote_storage/debian/debian-12-4.tar'
  - name: '12-5'
    src_path: 
      local: '/home/kate/TransferEfficiencyTool/test_data/debian/debian-12-5.tar'
      rsync: 'localhost:/home/kate/TransferEfficiencyTool/test_data/debian/debian-12-5.tar'
      zsync: 'http://localhost:8080/debian/debian-12-5.tar.zsync'
      zsync_local: '/var/www/remote_storage/debian/debian-12-5.tar'
  - name: '12-6'
    src_path: 
      local: '/home/kate/TransferEfficiencyTool/test_data/debian/debian-12-6.tar'
      rsync: 'localhost:/home/kate/TransferEfficiencyTool/test_data/debian/debian-12-6.tar'
      zsync: 'http://localhost:8080/debian/debian-12-6.tar.zsync'
      zsync_local: '/var/www/remote_storage/debian/debian-12-6.tar'
  - name: '12-7'
    src_path: 
      local: '/home/kate/TransferEfficiencyTool/test_data/debian/debian-12-7.tar'
      rsync: 'localhost:/home/kate/TransferEfficiencyTool/test_data/debian/debian-12-7.tar'
      zsync: 'http://localhost:8080/debian/debian-12-7.tar.zsync'
      zsync_local: '/var/www/remote_storage/debian/debian-12-7.tar'
  - name: '12-8'
    src_path: 
      local: '/home/kate/TransferEfficiencyTool/test_data/debian/debian-12-8.tar'
      rsync: 'localhost:/home/kate/TransferEfficiencyTool/test_data/debian/debian-12-8.tar'
      zsync: 'http://localhost:8080/debian/debian-12-8.tar.zsync'
      zsync_local: '/var/www/remote_storage/debian/debian-12-8.tar'
cas_transmitters: {}
other_transmitters:
  rsync:
    port: 22
  zsync:
    port: 8080
result_data_store: '/home/kate/TransferEfficiencyTool/measurements/debian_zsync/'
result_plot_store: '/home/kate/TransferEfficiencyTool/measurements/debian_zsync/'
dest_path: '/home/kate/TransferEfficiencyTool/results/debian/{}.tar'
