name: Models
cas_config:
  local_cache_store: '/home/kate/TransferEfficiencyTool/local_cache/models/'
  remote_storage:
    casync: 'localhost:/home/kate/TransferEfficiencyTool/remote_storage/models/'
    desync: 'http://127.0.0.1:8000/'
  index_storage: '/home/kate/TransferEfficiencyTool/index/models/'
  local_version_of_remote_storage: '/home/kate/TransferEfficiencyTool/remote_storage/models/'
  chunk_sizes: [8, 16, 32, 64, 96, 128, 192, 256, 384, 512]
versions:
  - name: '0'
    src_path: 
      local: '/home/kate/TransferEfficiencyTool/test_data/models/model_0.pth'
      rsync: 'localhost:/home/kate/TransferEfficiencyTool/test_data/models/model_0.pth'
  - name: '10'
    src_path:
      local: '/home/kate/TransferEfficiencyTool/test_data/models/model_10.pth'
      rsync: 'localhost:/home/kate/TransferEfficiencyTool/test_data/models/model_10.pth'
  - name: '20'
    src_path:
      local: '/home/kate/TransferEfficiencyTool/test_data/models/model_20.pth'
      rsync: 'localhost:/home/kate/TransferEfficiencyTool/test_data/models/model_20.pth'
  - name: '30'
    src_path:
      local: '/home/kate/TransferEfficiencyTool/test_data/models/model_30.pth'
      rsync: 'localhost:/home/kate/TransferEfficiencyTool/test_data/models/model_30.pth'
  - name: '40'
    src_path:
      local: '/home/kate/TransferEfficiencyTool/test_data/models/model_40.pth'
      rsync: 'localhost:/home/kate/TransferEfficiencyTool/test_data/models/model_40.pth'
  - name: '50'
    src_path:
      local: '/home/kate/TransferEfficiencyTool/test_data/models/model_50.pth'
      rsync: 'localhost:/home/kate/TransferEfficiencyTool/test_data/models/model_50.pth'
  - name: '60'
    src_path:
      local: '/home/kate/TransferEfficiencyTool/test_data/models/model_60.pth'
      rsync: 'localhost:/home/kate/TransferEfficiencyTool/test_data/models/model_60.pth'
  - name: '70'
    src_path:
      local: '/home/kate/TransferEfficiencyTool/test_data/models/model_70.pth'
      rsync: 'localhost:/home/kate/TransferEfficiencyTool/test_data/models/model_70.pth'
  - name: '80'
    src_path:
      local: '/home/kate/TransferEfficiencyTool/test_data/models/model_80.pth'
      rsync: 'localhost:/home/kate/TransferEfficiencyTool/test_data/models/model_80.pth'
  - name: '90'
    src_path:
      local: '/home/kate/TransferEfficiencyTool/test_data/models/model_90.pth'
      rsync: 'localhost:/home/kate/TransferEfficiencyTool/test_data/models/model_90.pth'
cas_transmitters:
  - casync
  - desync
other_transmitters:
  - rsync
result_data_store: '/home/kate/TransferEfficiencyTool/measurements/models/'
result_plot_store: '/home/kate/TransferEfficiencyTool/measurements/models/'
dest_path: '/home/kate/results/models/{}'
