name: Neovim
local_cache_store: '/home/kate/TransferEfficiencyTool/local_cache/neovim/'
remote_storage: 'http://127.0.0.1:8000/'
local_storage_for_casync_make: '/home/kate/TransferEfficiencyTool/remote_storage/neovim/'
index_storage: '/home/kate/TransferEfficiencyTool/index/neovim/'
versions: [
  ['7-0', '/home/kate/TransferEfficiencyTool/test_data/neovim/nvim-7-0', '/home/kate/TransferEfficiencyTool/results/neovim/nvim-7-0'],
  ['7-2', '/home/kate/TransferEfficiencyTool/test_data/neovim/nvim-7-2', '/home/kate/TransferEfficiencyTool/results/neovim/nvim-7-2'],
  ['8-0', '/home/kate/TransferEfficiencyTool/test_data/neovim/nvim-8-0', '/home/kate/TransferEfficiencyTool/results/neovim/nvim-8-0'], 
  ['9-0', '/home/kate/TransferEfficiencyTool/test_data/neovim/nvim-9-0', /home/kate/TransferEfficiencyTool/results/neovim/nvim-9-0'],
  ['9-1', '/home/kate/TransferEfficiencyTool/test_data/neovim/nvim-9-1', '/home/kate/TransferEfficiencyTool/results/neovim/nvim-9-1'],
  ['9-2', '/home/kate/TransferEfficiencyTool/test_data/neovim/nvim-9-2', '/home/kate/TransferEfficiencyTool/results/neovim/nvim-9-2'],
  ['9-4', '/home/kate/TransferEfficiencyTool/test_data/neovim/nvim-9-4', '/home/kate/TransferEfficiencyTool/results/neovim/nvim-9-4'],
  ['9-5', '/home/kate/TransferEfficiencyTool/test_data/neovim/nvim-9-5', '/home/kate/TransferEfficiencyTool/results/neovim/nvim-9-5']
]
